Main
Bendyk-Vitalii/angular-heroes-app pull request #8
Opened 2022-02-21 09:54 UTC by Bendyk-Vitalii

2022-02-21 11:13 UTC, AlekzandrM requested changes

2022-02-21 11:13 UTC, AlekzandrM commented on src/app/shared/services/auth.service.ts
> +  register(form: FormGroup, user: User, submitted: boolean = false): void {
form должна обрабатываться в компоненте. В сервисе логика логирования и регистрации

2022-02-21 11:13 UTC, AlekzandrM commented on src/app/shared/services/auth.service.ts
> +    this.router.navigate(['/homepage']);
this.router убрать из сервиса, это логика компонента

2022-02-21 11:13 UTC, AlekzandrM commented on src/app/shared/services/auth.service.ts
> +  private handleError(error: HttpErrorResponse) {
Можно делать отдельные сервиси для обработки ошибок, но это не стояло в задаче. Данный сервис отвечает только за идентификацию + мы не используем запросы на бэк, поэтому это тоже в компонент если необходимо

2022-02-21 11:13 UTC, AlekzandrM commented on src/environments/environment.ts
> +  firebase: {
это к принципу что не надо делать то что не просит заказчик)

2022-02-21 11:13 UTC, AlekzandrM commented on src/styles.scss
> +.card {
.card это точно надо глобально? Это все попадет в бандл... Зачем лишние стили?

2022-02-21 13:30 UTC, Bendyk-Vitalii commented on src/app/pages/hero-selection-page/hero-selection-page.component.ts
> +  constructor() { }
Они будут использоваться позже.

2022-02-21 13:45 UTC, Bendyk-Vitalii commented on src/app/pages/hero-selection-page/hero-selection-page.component.ts
> +  constructor() { }
он будет использоваться позже

2022-04-04 16:04 UTC, AlekzandrM requested changes

2022-05-17 21:51 UTC, AlekzandrM commented on src/app/shared/services/heroes.service.ts
> +    console.log(this.http.get<any>(`${environment.heroes.searchBy}/${id}`));
console.log

2022-05-17 21:51 UTC, AlekzandrM commented on src/app/pages/login-page/login-page.component.ts
>    form!: FormGroup;
Модификаторы доступа

2022-05-17 21:51 UTC, AlekzandrM commented on src/app/pages/login-page/login-page.component.html
> +          *ngIf="email?.errors?.['required'] || email.status !== 'INVALID'"
почему в одном случае email?.errors стоит символ "?" в другом email.status нет

2022-05-17 21:51 UTC, AlekzandrM commented on src/app/pages/hero-selection-page/hero-selection-page.component.ts
> +  loader!: TemplateRef<any>;
Модификаторы доступа

2022-05-17 21:51 UTC, AlekzandrM commented on src/app/pages/hero-selection-page/hero-selection-page.component.ts
> +  fetchHeroes$!: Observable<any>;
any

2022-05-17 21:51 UTC, AlekzandrM commented on src/app/pages/hero-selection-page/hero-selection-page.component.ts
> +    this.form = this.heroesService.formValidator();
я акцентировал внимание на создание формы не в сервисе + название метода formValidator что создает форму*

2022-05-17 21:51 UTC, AlekzandrM commented on src/app/pages/hero-selection-page/hero-selection-page.component.ts
> +  public fetchHeroes(getBy = 'a'): Observable<ServerResponse> {
ServerResponse сразу достань нужные поля если необходимо в пайпе map например. Этот интерфейс не понадобится и получать будешь нужный массив/объект героев

2022-05-17 21:51 UTC, AlekzandrM commented on src/app/pages/hero-selection-page/hero-selection-page.component.ts
> +    const { value }: any = this.form.get('searchByName');
мы обговаривали использовать this.form.get('searchByName').valueChanges *

2022-05-17 21:51 UTC, AlekzandrM commented on src/app/pages/hero-selection-page/hero-selection-page.component.ts
> +    this.fetchHeroes$ = this.fetchHeroes(e.innerHTML);
e.innerHTML ??

2022-05-26 11:10 UTC, AlekzandrM approved these changes

2022-05-26 11:10 UTC, AlekzandrM commented on src/app/pages/hero-selection-page/hero-selection-page.component.ts
> +    this.getHeroes();
В дополнение, лучше так же вынести в отдельный метод для прослушки событий на форме, например  initListeners() (если есть много контролов в форме). Этот метод в свою очередь запускает другие методы прослушки на конкретном контроле, например  this.selectNameListener(). В этом методе будет прослушиваться конкретный контрол, например this.NameControl.valueChanges

2022-05-26 11:10 UTC, AlekzandrM commented on src/app/shared/custom-validators.directive.ts
> -  Validators,
Удаляй весь код что закоменчен в этом файле

2022-05-26 11:10 UTC, AlekzandrM commented on src/app/shared/services/heroes.service.ts
> +  // selectHero(id: string): void {
комменты

2022-05-27 14:08 UTC, merged